name: tankdrum_learning
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  soundpool: ^2.3.0
  synchronized: ^3.0.0+2
  g_entities:
    path: ../flutter_frameworks/entities
  g_utils:
    path: ../flutter_frameworks/utils
  g_pages:
    path: ../flutter_frameworks/pages
  g_firestore:
    path: ../flutter_frameworks/firestore
  g_file_storage:
    path: ../flutter_frameworks/file_storage
  g_auths:
    path: ../flutter_frameworks/auths
  g_components:
    path: ../flutter_frameworks/components
  get: ^4.6.5
  video_player: ^2.4.7
  flutter_ogg_piano: ^1.1.3
  just_audio: ^0.9.30
  audioplayers: ^0.20.1
  tekartik_midi:
    git:
      url: https://github.com/tekartik/midi.dart
      ref: dart2_3
  file_picker: ^5.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/standard_notes/kalimba/
    - assets/standard_notes/guzheng/
    - assets/standard_notes/harp/
    - assets/standard_notes/tankdrum/
    - assets/standard_notes/tankdrum_source/
    - assets/standard_notes/piano/
    - assets/action_sounds/
    - assets/songs/

  fonts:
    - family: TankIcon
      fonts:
        - asset: fonts/TankIcon.ttf
