name: tankdrum_learning
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  soundpool: ^2.3.0
  audioplayers: ^1.0.1
  synchronized: ^3.0.0+2
  g_entities:
    path: ../flutter_frameworks/entities
  g_utils:
    path: ../flutter_frameworks/utils
  g_pages:
    path: ../flutter_frameworks/pages
  g_firestore:
    path: ../flutter_frameworks/firestore
  g_auths:
    path: ../flutter_frameworks/auths
  g_components:
    path: ../flutter_frameworks/components
  get: ^4.6.5
  video_player: ^2.4.7
  flutter_ogg_piano: ^1.1.3
  midi_player: ^0.2.0
  flutter_midi: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/note_sounds/
    - assets/note_sounds/kalimba/
    - assets/note_sounds/kalimba_reverb/
    - assets/note_sounds/guzheng/
    - assets/note_sounds/harp/
    - assets/note_sounds/tankdrum/
    - assets/note_sounds/steeldrum/
    - assets/backgrounds/
    - assets/app_sounds/
    - assets/NiceSteinwayv39.sf2

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
