import 'package:tankdrum_learning/models/song_note.dart';
import 'package:tankdrum_learning/models/song_sentence.dart';

class SongLib {
  static final List<SongSentence> castleInTheSky = [
    SongSentence([
      SongNote('B4', 1),
      SongNote('C#5', 1),
      SongNote('B3,D5', 1),
      SongNote('D4', 1),
      SongNote('F#4', 1),
      SongNote('C#5', 1),
      SongNote('D5', 1),
      SongNote('F#5', 2),
      SongNote('C#5,F#3', 1),
      SongNote('A3', 1),
      SongNote('C#4', 1),
      SongNote('F#4', 1),
      SongNote('A4', 2),
    ]),
    SongSentence([
      SongNote('F#4', 2),
      SongNote('B4,G3', 1),
      SongNote('B3', 1),
      SongNote('D4', 1),
      SongNote('A4', 1),
      SongNote('B4', 1),
      SongNote('D5', 2),
      SongNote('D4,A4', 2),
      SongNote('F#3', 2),
      SongNote('A3', 2),
    ]),
    SongSentence([
      SongNote('F#4', 2),
      SongNote('B3,G4', 3),
      SongNote('F#4', 1),
      SongNote('G4', 2),
      SongNote('D5', 2),
      SongNote('D4,F#4', 2),
      SongNote('A3', 2),
      SongNote('F#3', 1),
    ]),
    SongSentence([
      SongNote('D5', 1),
      SongNote('D5', 1),
      SongNote('D5', 1),
      SongNote('C#5,C#4', 2),
      SongNote('F#3', 1),
      SongNote('C#4', 1),
      SongNote('F#4', 1),
      SongNote('C#4', 1),
      SongNote('F#4', 1),
      SongNote('C#5', 1),
      SongNote('F#5', 3),
    ]),
    SongSentence([
      SongNote('B4', 1),
      SongNote('C#5', 1),
      SongNote('B3,D5', 1),
      SongNote('D4', 1),
      SongNote('F#4', 1),
      SongNote('C#5', 1),
      SongNote('D5', 1),
      SongNote('F#5', 2),
      SongNote('C#5,F#3', 1),
      SongNote('A3', 1),
      SongNote('C#4', 1),
    ]),
    SongSentence([
      SongNote('F#4', 1),
      SongNote('A4', 2),
      SongNote('F#4', 2),
      SongNote('B4,G3', 1),
      SongNote('B3', 1),
      SongNote('D4', 1),
      SongNote('A4', 1),
      SongNote('B4', 1),
      SongNote('D5', 2),
      SongNote('D4,A4', 2),
      SongNote('F#3', 2),
      SongNote('A3', 2),
    ]),
    SongSentence([
      SongNote('F#4', 2),
      SongNote('B3,G4', 2),
      SongNote('D5', 1),
      SongNote('C#5', 1),
      SongNote('D5', 1),
      SongNote('A3,E5', 1),
      SongNote('E5', 1),
      SongNote('C#4', 1),
      SongNote('F#5', 1),
      SongNote('D5,B3', 1),
      SongNote('D4', 1),
      SongNote('F#4', 1),
      SongNote('D4', 1),
      SongNote('D5,G3', 1),
      SongNote('C#5', 1),
      SongNote('B4', 2),
    ]),
    SongSentence([
      SongNote('C#5,A3', 1),
      SongNote('C#4', 1),
      SongNote('C#5', 2),
      SongNote('B4,B3', 2),
      SongNote('F#3', 2),
      SongNote('B3', 2),
      SongNote('D4', 1),
      SongNote('E4', 1),
      SongNote('D4,F#4', 2),
      SongNote('A3', 1),
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('A4', 2),
      SongNote('A3,E4', 3),
    ]),
    SongSentence([
      SongNote('C#4', 1),
      SongNote('A3', 2),
      SongNote('D4,B3', 2),
      SongNote('C#4', 1),
      SongNote('D4', 1),
      SongNote('F#4', 1),
      SongNote('F#4,F#3', 3),
      SongNote('A3', 2),
      SongNote('C#4', 2),
      SongNote('A3', 2),
      SongNote('B3,G3', 1),
      SongNote('C#4', 1),
      SongNote('D4', 2),
      SongNote('C#4,A3', 1),
      SongNote('D4', 1),
      SongNote('E4', 2),
      SongNote('D4,F#3', 2),
      SongNote('A3', 1),
      SongNote('B3,G4', 2),
      SongNote('F#4', 2),
      SongNote('E4,F#3', 2),
      SongNote('D4', 1),
    ]),
    SongSentence([
      SongNote('F#4,C#4', 2),
      SongNote('C#5', 2),
      SongNote('F#4', 3),
      SongNote('B4,B3', 1),
      SongNote('B3', 1),
      SongNote('D4', 1),
      SongNote('B4', 1),
      SongNote('A4,A3', 1),
      SongNote('C#4', 1),
      SongNote('E4', 1),
      SongNote('A4', 1),
      SongNote('C#4,F#4', 1),
      SongNote('E4', 1),
      SongNote('D4', 3),
      SongNote('D4', 1),
      SongNote('E4,G3', 2),
      SongNote('D4', 1),
      SongNote('E4', 3),
    ]),
    SongSentence([
      SongNote('A4', 1),
      SongNote('F#4,C#4', 1),
      SongNote('F#3', 1),
      SongNote('A3', 1),
      SongNote('D4', 1),
      SongNote('F#4', 2),
      SongNote('B4,B3', 1),
      SongNote('B3', 1),
      SongNote('D4', 1),
      SongNote('B4', 1),
      SongNote('A4,A3', 1),
      SongNote('C#4', 1),
      SongNote('E4', 1),
      SongNote('A4', 1),
      SongNote('C#4,F#4', 1),
      SongNote('E4', 1),
      SongNote('D4', 3),
      SongNote('D4', 1),
      SongNote('E4,G3', 2),
      SongNote('D4', 1),
      SongNote('E4', 3),
      SongNote('C#4', 2),
      SongNote('F#3,B3', 2)
    ])
  ];

  static final endlessLove = [
    SongSentence([
      SongNote('B3', 2),
      SongNote('F#4', 2),
      SongNote('C#4,A3', 4),
      SongNote('B3,G3', 1),
      SongNote('D4', 1),
      SongNote('E4', 1),
      SongNote('D4', 1),
      SongNote('F#4,A3', 4)
    ]),
    SongSentence([
      SongNote('B3,G3', 2),
      SongNote('B4', 2),
      SongNote('A4,A3', 1),
      SongNote('B4', 1),
      SongNote('A4', 1),
      SongNote('E4', 1),
      SongNote('F#4,D4', 1),
      SongNote('A3', 1),
      SongNote('D4', 1),
      SongNote('E4', 1),
      SongNote('D4,B3', 4),
    ]),
    SongSentence([
      SongNote('B3,G3', 2),
      SongNote('B4', 2),
      SongNote('A4,A3', 1),
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('G4', 1),
      SongNote('F#4,D4', 2),
      SongNote('E4,C#4', 2),
      SongNote('D4,B3', 1),
      SongNote('B3,G3', 2),
      SongNote('F#4', 2),
      SongNote('E4,A3', 3),
    ]),
    SongSentence([
      SongNote('C#4', 1),
      SongNote('B3,G3', 1),
      SongNote('F#3', 1),
      SongNote('B3', 1),
      SongNote('C#4', 1),
      SongNote('D4', 4),
      SongNote('B3', 1),
      SongNote('F#3', 1),
      SongNote('F#4,B3', 1),
      SongNote('F#3', 1),
      SongNote('C#4', 1),
      SongNote('F#3', 1),
      SongNote('C#4', 1),
      SongNote('F#3', 1),
      SongNote('B3,G3', 1),
    ]),
    SongSentence([
      SongNote('D4', 1),
      SongNote('E4', 1),
      SongNote('D4', 1),
      SongNote('F#4,D4', 1),
      SongNote('A3', 1),
      SongNote('D4', 1),
      SongNote('A3', 1),
      SongNote('B3,G3', 1),
      SongNote('D4', 1),
      SongNote('B4,G4', 1),
      SongNote('D4', 1),
      SongNote('A4,A3', 1),
      SongNote('B4', 1),
      SongNote('A4', 1),
      SongNote('E4', 1),
      SongNote('F#4,D4', 1),
    ]),
    SongSentence([
      SongNote('A3', 1),
      SongNote('D4', 1),
      SongNote('A3', 1),
      SongNote('D4', 1),
      SongNote('A3', 1),
      SongNote('D4', 1),
      SongNote('E4', 1),
      SongNote('B3,G3', 1),
      SongNote('D4', 1),
      SongNote('B4,G4', 1),
      SongNote('D4', 1),
      SongNote('A4,A3', 1),
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('G4', 1),
      SongNote('F#4,D4', 1),
    ]),
    SongSentence([
      SongNote('A3', 1),
      SongNote('E4,C#4', 1),
      SongNote('A3', 1),
      SongNote('D4,B3', 1),
      SongNote('F#3', 1),
      SongNote('B3', 1),
      SongNote('D4', 1),
      SongNote('B3,G3', 2),
      SongNote('F#4,D4', 2),
      SongNote('E4,A3', 1),
      SongNote('A3', 1),
      SongNote('E4', 1),
      SongNote('C#4', 1),
      SongNote('B3', 1),
      SongNote('F#3', 1),
    ]),
    SongSentence([
      SongNote('B3', 1),
      SongNote('F#3', 1),
      SongNote('B3', 1),
      SongNote('F#4', 1),
      SongNote('B3', 1),
      SongNote('C#4', 1),
      SongNote('D4,B3', 1),
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('D4', 1),
      SongNote('C#4,A3', 2),
      SongNote('A3', 2),
      SongNote('B3,G3', 1),
      SongNote('D4', 1),
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('F#4,D4', 1),
    ]),
    SongSentence([
      SongNote('A3', 1),
      SongNote('B3', 1),
      SongNote('C#4', 1),
      SongNote('D4,B3', 1),
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('D4', 1),
      SongNote('C#4,A3', 2),
      SongNote('A3', 2),
      SongNote('B3,G3', 1),
      SongNote('D4', 1),
      SongNote('E4', 1),
      SongNote('D4', 1),
      SongNote('D4,A3', 1),
    ]),
    SongSentence([
      SongNote('A3', 1),
      SongNote('B3', 1),
      SongNote('C#4', 1),
      SongNote('D4,B3', 1),
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('D4', 1),
      SongNote('C#4,A3', 2),
      SongNote('A3', 2),
      SongNote('B3,G3', 1),
      SongNote('D4', 1),
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('F#4,D4', 1),
    ]),
    SongSentence([
      SongNote('A3', 1),
      SongNote('B3', 1),
      SongNote('C#4', 1),
      SongNote('D4,B3', 1),
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('D4', 1),
      SongNote('C#4,A3', 2),
      SongNote('A3', 2),
      SongNote('B3,G3', 1),
      SongNote('D4', 1),
      SongNote('E4', 1),
      SongNote('D4', 1),
      SongNote('D4,A3', 1),
      SongNote('A3', 1),
      SongNote('B3', 1),
      SongNote('C#4', 1),
      SongNote('D4,B3', 1),
    ]),
    SongSentence([
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('D4', 1),
      SongNote('C#4,A3', 2),
      SongNote('A3', 2),
      SongNote('F#4,E4', 1),
      SongNote('D4', 1),
      SongNote('E4,D4', 1),
      SongNote('F#4', 1),
      SongNote('F#4,D4', 1),
      SongNote('A3', 1),
      SongNote('B3', 1),
      SongNote('C#4', 1),
      SongNote('D4', 1),
    ]),
    SongSentence([
      SongNote('E4,A3', 1),
      SongNote('F#4,D4', 1),
      SongNote('D4,A3', 1),
      SongNote('C#4,A3', 2),
      SongNote('A3', 2),
      SongNote('D4', 2),
      SongNote('C#4,A3', 2),
      SongNote('A3', 3),
      SongNote('C#4', 1),
      SongNote('B3', 1),
      SongNote('F#3', 1),
      SongNote('B3', 1),
      SongNote('C#4', 1),
      SongNote('D4', 2),
      SongNote('C#4', 1),
      SongNote('B3', 2)
    ])
  ];

  static final proudOfYou = [
    SongSentence([
      SongNote('F#4,A3', 2),
      SongNote('F#4', 1),
      SongNote('G4', 1),
      SongNote('A4,C#4', 2),
      SongNote('B4', 1),
      SongNote('C#5', 1),
      SongNote('D5,B3', 2),
      SongNote('F#4', 1),
      SongNote('G4', 1),
      SongNote('A4,A3', 4),
    ]),
    SongSentence([
      SongNote('A4', 2),
      SongNote('D4,B3', 4),
      SongNote('B4', 1),
      SongNote('A4,E4', 1),
      SongNote('D5', 1),
      SongNote('A4', 1),
      SongNote('D4', 1),
      SongNote('G4,E4', 3),
      SongNote('D4', 1),
      SongNote('E4', 2),
      SongNote('F#4', 2),
      SongNote('F#4,D4', 2),
      SongNote('F#4', 1),
      SongNote('G4', 1),
      SongNote('A4,C#4', 2),
    ]),
    SongSentence([
      SongNote('B4', 1),
      SongNote('C#5', 1),
      SongNote('D5,B3', 1),
      SongNote('D5', 1),
      SongNote('F#4', 1),
      SongNote('G4', 1),
      SongNote('A4,A3', 2),
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('G4,B3', 1),
      SongNote('F#4', 1),
      SongNote('G4,D5', 1),
      SongNote('D5,F#4', 1),
    ]),
    SongSentence([
      SongNote('E4', 1),
      SongNote('F#4', 1),
      SongNote('G4,E4', 1),
      SongNote('F#4', 1),
      SongNote('G4,E5', 1),
      SongNote('E5,A3', 1),
      SongNote('D5', 1),
      SongNote('C#5', 1),
      SongNote('D5,D4', 4),
      SongNote('E5', 1),
      SongNote('F#5,C#4', 1),
      SongNote('E5', 1),
      SongNote('D5', 1),
      SongNote('C#5', 1),
      SongNote('D5,B3', 3),
    ]),
    SongSentence([
      SongNote('D5', 1),
      SongNote('C#5,A3', 1),
      SongNote('A4', 1),
      SongNote('A4', 1),
      SongNote('D4', 1),
      SongNote('B4,G4', 3),
      SongNote('B4', 1),
      SongNote('A4,F#4', 1),
      SongNote('D4', 1),
      SongNote('D4', 1),
      SongNote('F#4', 1),
      SongNote('E4,B3', 3),
      SongNote('F#4', 1),
      SongNote('G4,A3', 1),
      SongNote('A4', 1),
      SongNote('D5', 1),
      SongNote('C#5', 1),
      SongNote('D5,D4', 3),
    ]),
    SongSentence([
      SongNote('E5', 1),
      SongNote('F#5,C#4', 1),
      SongNote('E5', 1),
      SongNote('D5', 1),
      SongNote('C#5', 1),
      SongNote('D5,B3', 3),
      SongNote('D5', 1),
      SongNote('C#5,A3', 1),
      SongNote('A4', 1),
      SongNote('A4', 1),
      SongNote('D4', 1),
      SongNote('B4,G4', 3),
      SongNote('B4', 1),
      SongNote('A4,A3', 1),
      SongNote('A4', 1),
      SongNote('D5', 1),
      SongNote('C#5', 1),
      SongNote('D4,D5', 1)
    ]),
  ];

  static final happyBirthDay = [
    SongSentence([
      SongNote('D4'),
      SongNote('D4'),
      SongNote('E4'),
      SongNote('D4'),
      SongNote('G4'),
      SongNote('F#4'),
    ]),
    SongSentence([
      SongNote('D4'),
      SongNote('D4'),
      SongNote('E4'),
      SongNote('D4'),
      SongNote('A4'),
      SongNote('G4'),
    ]),
    SongSentence([
      SongNote('D4'),
      SongNote('D4'),
      SongNote('D5'),
      SongNote('B4'),
      SongNote('G4'),
      SongNote('G4'),
      SongNote('F#4'),
    ]),
    SongSentence([
      SongNote('E4'),
      SongNote('D5'),
      SongNote('D5'),
      SongNote('B4'),
      SongNote('G4'),
      SongNote('A4'),
      SongNote('G4'),
    ])
  ];
}
