import 'package:tankdrum_learning/models/song_note.dart';

import 'note_link_type.dart';

class SongLib {
  static final List<SongNote> castleInTheSky = [
    SongNote('B4'),
    SongNote('C#5'),
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('D5'),
    SongNote('D4'),
    SongNote('F#4'),
    SongNote('C#5'),
    SongNote('D5'),
    SongNote('F#5')..beats = 2,
    SongNote('C#5')..linkType = NoteLinkType.one,
    SongNote('F#3'),
    SongNote('A3'),
    SongNote('C#4'),
    SongNote('F#4'),
    SongNote('A4')..beats = 2,
    SongNote('F#4')..beats = 2,
    SongNote('B4')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('B3'),
    SongNote('D4'),
    SongNote('A4'),
    SongNote('B4'),
    SongNote('D5')..beats = 2,
    SongNote('D4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('A4')..beats = 2,
    SongNote('F#3')..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('F#4')..beats = 2,
    SongNote('B3')
      ..linkType = NoteLinkType.one
      ..beats = 3,
    SongNote('G4')..beats = 3,
    SongNote('F#4'),
    SongNote('G4')..beats = 2,
    SongNote('D5')..beats = 2,
    SongNote('D4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('F#4')..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('F#3'),
    SongNote('D5'),
    SongNote('D5'),
    SongNote('D5'),
    SongNote('C#5')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('C#4')..beats = 2,
    SongNote('F#3'),
    SongNote('C#4'),
    SongNote('F#4'),
    SongNote('C#4'),
    SongNote('F#4'),
    SongNote('C#5'),
    SongNote('F#5')..beats = 3,
    SongNote('B4'),
    SongNote('C#5'),
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('D5'),
    SongNote('D4'),
    SongNote('F#4'),
    SongNote('C#5'),
    SongNote('D5'),
    SongNote('F#5')..beats = 2,
    SongNote('C#5')..linkType = NoteLinkType.one,
    SongNote('F#3'),
    SongNote('A3'),
    SongNote('C#4'),
    SongNote('F#4'),
    SongNote('A4')..beats = 2,
    SongNote('F#4')..beats = 2,
    SongNote('B4')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('B3'),
    SongNote('D4'),
    SongNote('A4'),
    SongNote('B4'),
    SongNote('D5')..beats = 2,
    SongNote('D4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('A4')..beats = 2,
    SongNote('F#3')..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('F#4')..beats = 2,
    SongNote('B3')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('G4')..beats = 2,
    SongNote('D5'),
    SongNote('C#5'),
    SongNote('D5'),
    SongNote('A3')..linkType = NoteLinkType.one,
    SongNote('E5'),
    SongNote('E5'),
    SongNote('C#4'),
    SongNote('F#5'),
    SongNote('D5')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('D4'),
    SongNote('F#4'),
    SongNote('D4'),
    SongNote('D5')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('C#5'),
    SongNote('B4')..beats = 2,
    SongNote('C#5')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('C#4'),
    SongNote('C#5')..beats = 2,
    SongNote('B4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('B3')..beats = 2,
    SongNote('F#3')..beats = 2,
    SongNote('B3')..beats = 2,
    SongNote('D4'),
    SongNote('E4'),
    SongNote('D4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('F#4')..beats = 2,
    SongNote('A3'),
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('A4')..beats = 2,
    SongNote('A3')
      ..linkType = NoteLinkType.one
      ..beats = 3,
    SongNote('E4')..beats = 3,
    SongNote('C#4'),
    SongNote('A3')..beats = 2,
    SongNote('D4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('B3')..beats = 2,
    SongNote('C#4'),
    SongNote('D4'),
    SongNote('F#4'),
    SongNote('F#4')
      ..linkType = NoteLinkType.one
      ..beats = 3,
    SongNote('F#3')..beats = 3,
    SongNote('A3')..beats = 2,
    SongNote('C#4')..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('C#4'),
    SongNote('D4')..beats = 2,
    SongNote('C#4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('D4'),
    SongNote('E4')..beats = 2,
    SongNote('D4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('F#3')..beats = 2,
    SongNote('A3'),
    SongNote('B3')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('G4')..beats = 2,
    SongNote('F#4')..beats = 2,
    SongNote('E4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('F#3')..beats = 2,
    SongNote('D4'),
    SongNote('F#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('C#4')..beats = 2,
    SongNote('C#5')..beats = 2,
    SongNote('F#4')..beats = 3,
    SongNote('B4')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('B3'),
    SongNote('D4'),
    SongNote('B4'),
    SongNote('A4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('C#4'),
    SongNote('E4'),
    SongNote('A4'),
    SongNote('C#4')..linkType = NoteLinkType.one,
    SongNote('F#4'),
    SongNote('E4'),
    SongNote('D4')..beats = 3,
    SongNote('D4'),
    SongNote('E4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('G3')..beats = 2,
    SongNote('D4'),
    SongNote('E4')..beats = 3,
    SongNote('A4'),
    SongNote('F#4')..linkType = NoteLinkType.one,
    SongNote('C#4'),
    SongNote('F#3'),
    SongNote('A3'),
    SongNote('D4'),
    SongNote('F#4')..beats = 2,
    SongNote('B4')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('B3'),
    SongNote('D4'),
    SongNote('B4'),
    SongNote('A4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('C#4'),
    SongNote('E4'),
    SongNote('A4'),
    SongNote('C#4')..linkType = NoteLinkType.one,
    SongNote('F#4'),
    SongNote('E4'),
    SongNote('D4')..beats = 3,
    SongNote('D4'),
    SongNote('E4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('G3')..beats = 2,
    SongNote('D4'),
    SongNote('E4')..beats = 3,
    SongNote('C#4')..beats = 2,
    SongNote('F#3')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('B3')..beats = 2,
  ];

  static final endlessLove = [
    SongNote('B3')..beats = 2,
    SongNote('F#4')..beats = 2,
    SongNote('C#4')
      ..linkType = NoteLinkType.one
      ..beats = 4,
    SongNote('A3')..beats = 4,
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('D4'),
    SongNote('E4'),
    SongNote('D4'),
    SongNote('F#4')
      ..linkType = NoteLinkType.one
      ..beats = 4,
    SongNote('A3')..beats = 4,
    SongNote('B3')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('G3')..beats = 2,
    SongNote('B4')..beats = 2,
    SongNote('A4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('B4'),
    SongNote('A4'),
    SongNote('E4'),
    SongNote('F#4')..linkType = NoteLinkType.one,
    SongNote('D4'),
    SongNote('A3'),
    SongNote('D4'),
    SongNote('E4'),
    SongNote('D4')
      ..linkType = NoteLinkType.one
      ..beats = 4,
    SongNote('B3')..beats = 4,
    SongNote('B3')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('G3')..beats = 2,
    SongNote('B4')..beats = 2,
    SongNote('A4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('G4'),
    SongNote('F#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('D4')..beats = 2,
    SongNote('E4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('C#4')..beats = 2,
    SongNote('D4')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('B3')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('G3')..beats = 2,
    SongNote('F#4')..beats = 2,
    SongNote('E4')
      ..linkType = NoteLinkType.one
      ..beats = 3,
    SongNote('A3')..beats = 3,
    SongNote('C#4'),
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('F#3'),
    SongNote('B3'),
    SongNote('C#4'),
    SongNote('D4')..beats = 4,
    SongNote('B3'),
    SongNote('F#3'),
    SongNote('F#4')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('F#3'),
    SongNote('C#4'),
    SongNote('F#3'),
    SongNote('C#4'),
    SongNote('F#3'),
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('D4'),
    SongNote('E4'),
    SongNote('D4'),
    SongNote('F#4')..linkType = NoteLinkType.one,
    SongNote('D4'),
    SongNote('A3'),
    SongNote('D4'),
    SongNote('A3'),
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('D4'),
    SongNote('B4')..linkType = NoteLinkType.one,
    SongNote('G4'),
    SongNote('D4'),
    SongNote('A4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('B4'),
    SongNote('A4'),
    SongNote('E4'),
    SongNote('F#4')..linkType = NoteLinkType.one,
    SongNote('D4'),
    SongNote('A3'),
    SongNote('D4'),
    SongNote('A3'),
    SongNote('D4'),
    SongNote('A3'),
    SongNote('D4'),
    SongNote('E4'),
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('D4'),
    SongNote('B4')..linkType = NoteLinkType.one,
    SongNote('G4'),
    SongNote('D4'),
    SongNote('A4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('G4'),
    SongNote('F#4')..linkType = NoteLinkType.one,
    SongNote('D4'),
    SongNote('A3'),
    SongNote('E4')..linkType = NoteLinkType.one,
    SongNote('C#4'),
    SongNote('A3'),
    SongNote('D4')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('F#3'),
    SongNote('B3'),
    SongNote('D4'),
    SongNote('B3')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('G3')..beats = 2,
    SongNote('F#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('D4')..beats = 2,
    SongNote('E4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('A3'),
    SongNote('E4'),
    SongNote('C#4'),
    SongNote('B3'),
    SongNote('F#3'),
    SongNote('B3'),
    SongNote('F#3'),
    SongNote('B3'),
    SongNote('F#4'),
    SongNote('B3'),
    SongNote('C#4'),
    SongNote('D4')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('D4'),
    SongNote('C#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('D4'),
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('F#4')..linkType = NoteLinkType.one,
    SongNote('D4'),
    SongNote('A3'),
    SongNote('B3'),
    SongNote('C#4'),
    SongNote('D4')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('D4'),
    SongNote('C#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('D4'),
    SongNote('E4'),
    SongNote('D4'),
    SongNote('D4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('A3'),
    SongNote('B3'),
    SongNote('C#4'),
    SongNote('D4')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('D4'),
    SongNote('C#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('D4'),
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('F#4')..linkType = NoteLinkType.one,
    SongNote('D4'),
    SongNote('A3'),
    SongNote('B3'),
    SongNote('C#4'),
    SongNote('D4')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('D4'),
    SongNote('C#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('B3')..linkType = NoteLinkType.one,
    SongNote('G3'),
    SongNote('D4'),
    SongNote('E4'),
    SongNote('D4'),
    SongNote('D4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('A3'),
    SongNote('B3'),
    SongNote('C#4'),
    SongNote('D4')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('D4'),
    SongNote('C#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('F#4')..linkType = NoteLinkType.one,
    SongNote('E4'),
    SongNote('D4'),
    SongNote('E4')..linkType = NoteLinkType.one,
    SongNote('D4'),
    SongNote('F#4'),
    SongNote('F#4')..linkType = NoteLinkType.one,
    SongNote('D4'),
    SongNote('A3'),
    SongNote('B3'),
    SongNote('C#4'),
    SongNote('D4'),
    SongNote('E4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('F#4')..linkType = NoteLinkType.one,
    SongNote('D4'),
    SongNote('D4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('C#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('D4')..beats = 2,
    SongNote('C#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('A3')..beats = 3,
    SongNote('C#4'),
    SongNote('B3'),
    SongNote('F#3'),
    SongNote('B3'),
    SongNote('C#4'),
    SongNote('D4')..beats = 2,
    SongNote('C#4'),
    SongNote('B3')..beats = 2,
  ];

  static final proudOfYou = [
    SongNote('F#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('F#4'),
    SongNote('G4'),
    SongNote('A4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('C#4')..beats = 2,
    SongNote('B4'),
    SongNote('C#5'),
    SongNote('D5')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('B3')..beats = 2,
    SongNote('F#4'),
    SongNote('G4'),
    SongNote('A4')
      ..linkType = NoteLinkType.one
      ..beats = 4,
    SongNote('A3')..beats = 4,
    SongNote('A4')..beats = 2,
    SongNote('D4')
      ..linkType = NoteLinkType.one
      ..beats = 4,
    SongNote('B3')..beats = 4,
    SongNote('B4'),
    SongNote('A4')..linkType = NoteLinkType.one,
    SongNote('E4'),
    SongNote('D5'),
    SongNote('A4'),
    SongNote('D4'),
    SongNote('G4')
      ..linkType = NoteLinkType.one
      ..beats = 3,
    SongNote('E4')..beats = 3,
    SongNote('D4'),
    SongNote('E4')..beats = 2,
    SongNote('F#4')..beats = 2,
    SongNote('F#4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('D4')..beats = 2,
    SongNote('F#4'),
    SongNote('G4'),
    SongNote('A4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('C#4')..beats = 2,
    SongNote('B4'),
    SongNote('C#5'),
    SongNote('D5')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('D5'),
    SongNote('F#4'),
    SongNote('G4'),
    SongNote('A4')
      ..linkType = NoteLinkType.one
      ..beats = 2,
    SongNote('A3')..beats = 2,
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('G4')..linkType = NoteLinkType.one,
    SongNote('B3'),
    SongNote('F#4'),
    SongNote('G4')..linkType = NoteLinkType.one,
    SongNote('D5'),
    SongNote('D5')..linkType = NoteLinkType.one,
    SongNote('F#4'),
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('G4')..linkType = NoteLinkType.one,
    SongNote('E4'),
    SongNote('F#4'),
    SongNote('G4')..linkType = NoteLinkType.one,
    SongNote('E5'),
    SongNote('E5')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('D5'),
    SongNote('C#5'),
    SongNote('D5')
      ..linkType = NoteLinkType.one
      ..beats = 4,
    SongNote('D4')..beats = 4,
    SongNote('E5'),
    SongNote('F#5')..linkType = NoteLinkType.one,
    SongNote('C#4'),
    SongNote('E5'),
    SongNote('D5'),
    SongNote('C#5'),
    SongNote('D5')
      ..linkType = NoteLinkType.one
      ..beats = 3,
    SongNote('B3')..beats = 3,
    SongNote('D5'),
    SongNote('C#5')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('A4'),
    SongNote('A4'),
    SongNote('D4'),
    SongNote('B4')
      ..linkType = NoteLinkType.one
      ..beats = 3,
    SongNote('G4')..beats = 3,
    SongNote('B4'),
    SongNote('A4')..linkType = NoteLinkType.one,
    SongNote('F#4'),
    SongNote('D4'),
    SongNote('D4'),
    SongNote('F#4'),
    SongNote('E4')
      ..linkType = NoteLinkType.one
      ..beats = 3,
    SongNote('B3')..beats = 3,
    SongNote('F#4'),
    SongNote('G4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('A4'),
    SongNote('D5'),
    SongNote('C#5'),
    SongNote('D5')
      ..linkType = NoteLinkType.one
      ..beats = 3,
    SongNote('D4')..beats = 3,
    SongNote('E5'),
    SongNote('F#5')..linkType = NoteLinkType.one,
    SongNote('C#4'),
    SongNote('E5'),
    SongNote('D5'),
    SongNote('C#5'),
    SongNote('D5')
      ..linkType = NoteLinkType.one
      ..beats = 3,
    SongNote('B3')..beats = 3,
    SongNote('D5'),
    SongNote('C#5')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('A4'),
    SongNote('A4'),
    SongNote('D4'),
    SongNote('B4')
      ..linkType = NoteLinkType.one
      ..beats = 3,
    SongNote('G4')..beats = 3,
    SongNote('B4'),
    SongNote('A4')..linkType = NoteLinkType.one,
    SongNote('A3'),
    SongNote('A4'),
    SongNote('D5'),
    SongNote('C#5'),
    SongNote('D4')..linkType = NoteLinkType.one,
    SongNote('D5'),
  ];

  static final happyBirthDay = [
    SongNote('D4'),
    SongNote('D4'),
    SongNote('E4'),
    SongNote('D4'),
    SongNote('G4'),
    SongNote('F#4'),
    SongNote('D4'),
    SongNote('D4'),
    SongNote('E4'),
    SongNote('D4'),
    SongNote('A4'),
    SongNote('G4'),
    SongNote('D4'),
    SongNote('D4'),
    SongNote('D5'),
    SongNote('B4'),
    SongNote('G4'),
    SongNote('G4'),
    SongNote('F#4'),
    SongNote('E4'),
    SongNote('D5'),
    SongNote('D5'),
    SongNote('B4'),
    SongNote('G4'),
    SongNote('A4'),
    SongNote('G4'),
  ];
}
