// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgcc5ngAzwHk9et0xloly9_envZvnAoGs',
    appId: '1:981372260989:web:582513c417e46fbdaf9714',
    messagingSenderId: '981372260989',
    projectId: 'oceanic-base-250909',
    authDomain: 'oceanic-base-250909.firebaseapp.com',
    storageBucket: 'oceanic-base-250909.appspot.com',
    measurementId: 'G-2DPV4WNPV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD294vcxfsXcT9BWUxzFH3FrwlPMRDc0E0',
    appId: '1:981372260989:android:bd78a72528868507af9714',
    messagingSenderId: '981372260989',
    projectId: 'oceanic-base-250909',
    storageBucket: 'oceanic-base-250909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdRxQ_SaJODw6_auYX_uPOX2s2RnP_D54',
    appId: '1:981372260989:ios:7f34264d56de45caaf9714',
    messagingSenderId: '981372260989',
    projectId: 'oceanic-base-250909',
    storageBucket: 'oceanic-base-250909.appspot.com',
    iosClientId: '981372260989-qr9jpha9s40evddk9q7uikpfthglnua1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tankdrumLearning',
  );
}
